version: '3.3'
services:
  couch:
    image: apache/couchdb:2.2.0
    container_name: couch
    volumes:
     - ./containers/couchdb-local.ini:/opt/couchdb/etc/local.ini
    ports:
     - "6984:5984"
    expose:
     - 5984
    extra_hosts:
     - "upstream: ${UPSTREAM_HOST}"

  initRep:
    image: node:8
    container_name: initRep
    links:
     - couch
    extra_hosts:
     - "upstream: ${UPSTREAM_HOST}"
    volumes:
     - ./containers:/srv/software/offline_sync
     - ./status:/srv/status
    entrypoint:
     - node
     - /srv/software/offline_sync/js/initialReplication
    environment:
     - SATELLITE_COUCH_URL=http://medic:pwd123@couch:5984
     - UPSTREAM_API_URL=http://admin:pass@upstream:5988

  api:
    image: node:8
    container_name: api
    links:
     - couch
    volumes:
     - ./containers:/srv/software/offline_sync
     - ./status:/srv/status
    entrypoint:
     - node
     - /srv/software/offline_sync/js/api
    environment:
     - API_SKIP_STARTUP=1
     - SKIP_API_EXTRACTION=0
     - API_PATH=/srv/software/medic-api
     - SATELLITE_COUCH_URL=http://medic:pwd123@couch:5984
     - COUCH_NODE_NAME=couchdb@satellite
     - COUCH_URL=http://medic:pwd123@couch:5984/medic
     - API_PORT=5988
    ports:
     - "6988:5988"

  sync:
    image: node:8
    container_name: sync
    links:
     - couch
     - api
    volumes:
     - ./containers:/srv/software/offline_sync
    extra_hosts:
     - "upstream: ${UPSTREAM_HOST}"
    entrypoint:
     - node
     - /srv/software/offline_sync/js/continuousReplication
    environment:
      - SATELLITE_COUCH_URL=http://medic:pwd123@couch:5984
      - UPSTREAM_API_URL=http://admin:pass@upstream:5988
      - SATELLITE_API_URL=http://api:5988
    
  nginx:
    image: nginx
    container_name: nginx
    links:
     - api
    ports:
     - 443:443
    volumes:
     - ./containers/nginx.conf:/etc/nginx/conf.d/default.conf
    secrets:
     - nginx.crt
     - nginx.key
  
secrets:
  nginx.crt:
    file: "./config/${CONFIGURATION:-dev}/satellite.crt"
  nginx.key:
    file: "./config/${CONFIGURATION:-dev}/satellite.key"
  