#!/bin/bash

rm /root/.horticulturalist.lock 2> /dev/null
/srv/software/horticulturalist/bin/svc-stop medic-api 2> /dev/null

echo Launching initial replication script
cd /srv/software/offline_sync
node js/initialReplication || { echo 'FATAL: Initial replication failure'; exit -1; }

export COUCH_URL="${SATELLITE_COUCH_URL}/medic"

echo Launching horticulturalist
cd /srv/software/horticulturalist
node src --satellite || { echo 'FATAL: Horticulturalist failure'; exit -1; }
